### ISSUE TITLE
Problem with creating first files/folders

### ISSUE THREAD

**Issue by oxk4r01** [joshmu/vscode-create-relative-file#1]
I get allways the error 'Some files/folders already exist or could not be created' for the very first one. At least inside a workspace.
If I create the first file/folder by myself then, the extension works for the onward files/folders without throwing that error anymore.

**Comment by joshmu** [comment]
Hi @oxk4r01
When I have an open empty workspace _create relative file_ will generate a file based on the workspace path.
Could you provide me with additional information on how to reproduce this issue.

**Comment by joshmu** [comment]
Closing this issue. Happy to reopen if necessary.
